name = "blog"
main = "src/app.ts"
compatibility_date = "2025-08-11"
assets = { directory = "public" }

[[d1_databases]]
binding = "DB"
database_name = "blog"
database_id = "81a48e55-aba0-4ce2-8c7c-c7503c7f08d1"

[[routes]]
pattern = "mizuta-c5.me"
custom_domain = true

[[routes]]
pattern = "www.mizuta-c5.me"
custom_domain = true